### ISSUE TITLE
LocalDateTime1.java file throw a Exception

### ISSUE THREAD

**Issue by dinghuang** [winterbe/java8-tutorial#47]
`WEDNESDAY
DECEMBER
1439
Wed Dec 31 23:59:59 CST 2014
Exception in thread "main" java.time.format.DateTimeParseException: Text 'Nov 03, 2014 - 07:13' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDateTime.parse(LocalDateTime.java:492)
	at com.winterbe.java8.samples.time.LocalDateTime1.main(LocalDateTime1.java:42)

Process finished with exit code 1`

It's happen at 
` DateTimeFormatter formatter =
                DateTimeFormatter
                        .ofPattern("MMM dd, yyyy - HH:mm");

        LocalDateTime parsed = LocalDateTime.parse("Nov 03, 2014 - 07:13", formatter);
        String string = parsed.format(formatter);
        System.out.println(string);`

**Comment by stardustman** [comment]
I also find this bug, but the author don't fix it.
